version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: yana
      POSTGREA_PASSWORD: yana1234
      POSTGRES_DB: accommodation_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yana" ]
      interval: 30s
      timeout: 30s
      retries: 3
