@startuml

abstract class AbstractEntity {
- id: Long
- isDeleted : boolean
}
interface UserDetails
interface GrantedAuthority

class Accommodation {
- type : Type
- location : Location
- size : String
- amenities : Set<Amenity>
- dailyRate : BigDecimal
- availability : Integer
}

class Location {
- country : String
- city : String
- region : String
- zipCode : String
- address : String
- description : String
}

class Amenity {
- title : String
- description : String
}

class Role {
- name : RoleName
}


class User {
- email : String
- password : String
- firstName : String
- lastName : String
- role: Role
}

class Booking {
- checkInDate : LocalDate
- checkOutDate : LocalDate
- accommodation : Accommodation
- user : User
- status : Status
}

class Payment {
- status : Status
- dateTimeCreated : LocalDateTime
- booking : Booking
- amountToPay : BigDecimal
- sessionUrl : URL
- sessionID : String
}

enum Type {
    APARTMENT,
    GUEST_HOUSE,
    HOSTEL,
    HOTEL,
    HOUSE,
    VACATION_HOME,
    VILLA
}

enum RoleName {
    CUSTOMER,
    MANAGER,
    ADMIN
}

enum Status {
    PENDING,
    CONFIRMED,
    CANCELED,
    EXPIRED,
    PAID
}

note "org.springframework.security.core" as MyNote
MyNote .. UserDetails
MyNote .. GrantedAuthority

UserDetails <|.. User
GrantedAuthority <|.. Role

Booking --|> AbstractEntity
User -|> AbstractEntity
Role -|> AbstractEntity
Accommodation --|> AbstractEntity
Location --|> AbstractEntity
AbstractEntity <|- Payment
Amenity --|> AbstractEntity

User "n" o-- "1" Role
Booking "n" --o "1" User
Location "1" o- "1" Accommodation
Accommodation "n" --o "n" Amenity
Booking "n" --o "1" Accommodation
Booking "1" *-- "1" Payment

RoleName .> Role
Accommodation <. Type
Booking <. Status
Status ..> Payment

@enduml
